services:
  db:
    image: postgres:14
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: application_tracker_final_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
