source 'https://rubygems.org'

ruby '~> 3.3.0'

gem 'rails', '~> 7.2.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'rack-cors'
gem 'jbuilder', '~> 2.13'
gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'sprockets-rails'
gem 'logger'
gem 'mutex_m'
gem 'drb'

group :development, :test do
  gem 'byebug', platforms: [:mri, :windows]
  gem 'minitest', '~> 5.25'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver', '>= 4.11'
end

gem 'tzinfo-data', platforms: [:windows, :jruby]
